FROM balenalib/%%BALENA_MACHINE_NAME%%:buster

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

RUN install_packages apache2

COPY start.sh /usr/src/

CMD [ "/bin/bash", "/usr/src/start.sh" ]
